"""
Seed detailed English descriptions for all courses.
Run once (re-run safe, overwrites): python3 seed_descriptions.py
Each description includes: Course Overview, Learning Objectives,
Topics Covered, Skills Gained, and the Prerequisite (read from the DB).
"""
import sqlite3

# code: (overview, [objectives], [topics], [skills])
COURSES = {
"H 101": ("Develops English language proficiency for academic and professional contexts. The course strengthens reading, writing, listening, and speaking skills with a focus on technical and scientific communication.",
 ["Read and comprehend academic and technical texts", "Write clear, well-structured paragraphs and short essays", "Communicate effectively in academic discussions"],
 ["Reading comprehension strategies", "Academic vocabulary building", "Grammar in context", "Paragraph and essay structure", "Listening and presentation basics"],
 ["Academic reading and writing", "Professional communication", "Vocabulary for technical fields"]),
"BS 104": ("Introduces the fundamentals of electronics that underpin modern computing hardware. Students study electronic components and circuits and learn how they combine to form functional digital systems.",
 ["Understand the behavior of basic electronic components", "Analyze simple analog and digital circuits", "Relate electronic principles to computer hardware"],
 ["Semiconductors and diodes", "Transistors and amplifiers", "Operational amplifiers", "Digital logic basics", "Power supplies and signals"],
 ["Circuit analysis", "Reading electronic schematics", "Hardware fundamentals"]),
"CS 102": ("Teaches structured programming using a high-level language. Students move from basic syntax to writing complete programs that solve real problems, building the foundation for all later programming courses.",
 ["Translate problems into algorithmic solutions", "Write, test, and debug structured programs", "Use core data types and control structures fluently"],
 ["Variables, data types, and expressions", "Conditional statements and loops", "Functions and parameter passing", "Arrays and strings", "Basic file input/output", "Debugging techniques"],
 ["Problem solving with code", "Structured programming", "Debugging and testing"]),
"CS 101": ("A broad introduction to the discipline of computer science. The course surveys the history of computing, how computers represent and process information, and the major fields a computer scientist can specialize in.",
 ["Describe the main components of a computer system", "Convert between number systems and represent data digitally", "Identify the major branches of computer science"],
 ["History of computing", "Number systems and data representation", "Hardware and software overview", "Operating systems and networks at a glance", "Fields of computer science"],
 ["Computational thinking", "Technical literacy", "Foundation for specialization choices"]),
"IS 105": ("Introduces information systems and their role in modern organizations. Students learn how data becomes information and how systems are planned, built, and used to support decision making.",
 ["Differentiate types of information systems", "Understand the system development life cycle", "Recognize the role of data in organizational decisions"],
 ["IS concepts and components", "Transaction processing and management systems", "Decision support systems", "System development life cycle", "Ethical and social issues in IS"],
 ["Systems thinking", "Business-technology alignment", "Requirements awareness"]),
"BS 101": ("Covers single-variable calculus, the mathematical backbone of science and engineering. Students master limits, derivatives, and integrals and apply them to real-world rate and area problems.",
 ["Evaluate limits and analyze continuity", "Differentiate and integrate standard functions", "Apply calculus to optimization and area problems"],
 ["Limits and continuity", "Differentiation rules and applications", "Definite and indefinite integrals", "Applications of integration", "Transcendental functions"],
 ["Analytical reasoning", "Mathematical modeling", "Foundation for probability and algorithms"]),
"H 203": ("Trains students to produce professional technical documents. The course covers the full writing process from gathering information to producing polished, well-cited reports and documentation.",
 ["Structure technical reports effectively", "Present data using tables and figures", "Apply correct citation and referencing"],
 ["Report structure and planning", "Technical style and clarity", "Data presentation", "Citation and plagiarism", "Proposals and documentation"],
 ["Technical writing", "Documentation", "Professional presentation of information"]),
"CS 104": ("Introduces the engineering discipline behind building quality software. Students explore the software life cycle, development methodologies, and the basics of requirements and design.",
 ["Describe the phases of the software life cycle", "Compare development methodologies such as waterfall and agile", "Produce basic requirements and design artifacts"],
 ["Software process models", "Requirements engineering basics", "Basic system modeling (UML)", "Software quality concepts", "Introduction to project management"],
 ["Process-oriented thinking", "Requirements analysis", "Team-based development awareness"]),
"BS 103": ("Covers probability theory and statistical methods used throughout computing, from algorithm analysis to machine learning. Emphasis is placed on modeling uncertainty and drawing conclusions from data.",
 ["Compute probabilities of simple and compound events", "Work with random variables and standard distributions", "Perform estimation and hypothesis testing"],
 ["Probability axioms and counting", "Random variables", "Binomial, Poisson, and normal distributions", "Sampling and estimation", "Hypothesis testing and correlation"],
 ["Statistical reasoning", "Data analysis", "Foundation for ML and simulation"]),
"H 202": ("Explores the concept and history of human rights and their role in society. The course connects international principles to everyday professional and civic life.",
 ["Explain the historical development of human rights", "Identify key international declarations and conventions", "Relate rights principles to professional conduct"],
 ["Concepts and origins of human rights", "International declarations", "Rights and responsibilities", "Human rights in the digital age"],
 ["Civic awareness", "Ethical reasoning", "Social responsibility"]),
"CS 103": ("Builds on basic programming to introduce the object-oriented paradigm. Students learn to model real-world entities as classes and design reusable, maintainable software components.",
 ["Design classes that encapsulate data and behavior", "Apply inheritance and polymorphism correctly", "Build small object-oriented applications"],
 ["Classes and objects", "Encapsulation and access control", "Inheritance and polymorphism", "Abstract classes and interfaces", "Exception handling", "Intro to UML class diagrams"],
 ["Object-oriented design", "Code reuse", "Building maintainable software"]),
"H 103": ("Develops the soft skills every professional needs: creative thinking, structured problem solving, and confident communication, practiced through individual and team activities.",
 ["Apply idea-generation techniques such as brainstorming", "Work effectively within a team", "Deliver clear presentations"],
 ["Creative and critical thinking", "Problem-solving frameworks", "Teamwork and collaboration", "Presentation skills", "Time management"],
 ["Creativity", "Communication", "Collaboration"]),
"BS 102": ("Covers the discrete mathematical structures on which computer science is built. Topics range from logic and proofs to graphs, providing the language used in algorithms and databases.",
 ["Construct and evaluate logical arguments and proofs", "Work with sets, relations, and functions", "Apply counting techniques and basic graph theory"],
 ["Propositional and predicate logic", "Proof techniques and induction", "Sets, relations, and functions", "Combinatorics", "Graphs and trees"],
 ["Formal reasoning", "Proof writing", "Foundation for algorithms and databases"]),
"IS 207": ("Introduces the technologies of the web from the browser to the server. Students build interactive pages and learn how client and server cooperate to deliver web applications.",
 ["Build structured pages with HTML and style them with CSS", "Add interactivity using JavaScript", "Understand the client-server model and HTTP"],
 ["HTML5 structure and forms", "CSS layout and responsive design", "JavaScript and the DOM", "HTTP and the client-server model", "Introduction to server-side processing"],
 ["Front-end development", "Web fundamentals", "Building interactive interfaces"]),
"IS 206": ("Covers the theory and practice of relational databases. Students design schemas from requirements, normalize them, and query data using SQL.",
 ["Model data using entity-relationship diagrams", "Normalize relational schemas", "Write SQL queries for data definition and manipulation"],
 ["Database concepts and architecture", "ER modeling", "The relational model", "Normalization (1NF-3NF)", "SQL: DDL, DML, joins, and aggregation"],
 ["Database design", "SQL querying", "Data modeling"]),
"CS 202": ("Studies how computers are organized internally, from the processor datapath to memory and I/O. Students learn how software instructions are actually executed by hardware.",
 ["Explain CPU organization and the instruction cycle", "Analyze memory hierarchy behavior", "Understand instruction set architecture concepts"],
 ["CPU datapath and control", "Instruction sets and addressing modes", "Memory hierarchy and caching", "Input/output organization", "Performance measurement"],
 ["Hardware-software interface understanding", "Performance analysis", "Low-level systems insight"]),
"BS 202": ("Introduces operations research, the science of optimal decision making. Students formulate real problems as mathematical models and solve them with systematic techniques.",
 ["Formulate problems as linear programs", "Solve LPs graphically and with the simplex method", "Model transportation and assignment problems"],
 ["Linear programming formulation", "Graphical and simplex solutions", "Duality", "Transportation and assignment models", "Decision analysis"],
 ["Optimization modeling", "Quantitative decision making", "Analytical problem solving"]),
"CS 201": ("Covers the classic data structures every programmer must master. Students implement each structure, analyze its performance, and learn to choose the right one for a problem.",
 ["Implement linear and hierarchical data structures", "Analyze operations using Big-O notation", "Select appropriate structures for given problems"],
 ["Complexity analysis", "Linked lists, stacks, and queues", "Trees and binary search trees", "Heaps and priority queues", "Hash tables", "Graph representations"],
 ["Efficient programming", "Algorithmic analysis", "Implementation skills"]),
"BS 201": ("Covers linear algebra, the mathematics of vectors and matrices used in graphics, machine learning, and scientific computing.",
 ["Solve systems of linear equations", "Perform matrix operations and compute determinants", "Find eigenvalues and eigenvectors"],
 ["Vectors and matrices", "Systems of linear equations", "Determinants and inverses", "Vector spaces", "Eigenvalues and eigenvectors"],
 ["Mathematical foundations for graphics and ML", "Matrix computation", "Abstract reasoning"]),
"CS 203": ("Teaches how to design efficient algorithms and rigorously analyze their performance. Students study the major design paradigms and apply them to classic computational problems.",
 ["Analyze time and space complexity formally", "Apply divide-and-conquer, greedy, and dynamic programming", "Recognize NP-completeness at an introductory level"],
 ["Asymptotic analysis and recurrences", "Divide and conquer", "Greedy algorithms", "Dynamic programming", "Graph algorithms (shortest paths, MST)", "Intro to NP-completeness"],
 ["Algorithm design", "Complexity analysis", "Optimization thinking"]),
"CS 204": ("Covers the design of operating systems — the software layer that manages all hardware resources. Students study how an OS runs many programs at once safely and efficiently.",
 ["Explain process and thread management", "Apply CPU scheduling and synchronization techniques", "Describe memory and file system management"],
 ["Processes and threads", "CPU scheduling", "Synchronization and deadlocks", "Memory management and virtual memory", "File systems"],
 ["Systems-level thinking", "Concurrency awareness", "Resource management understanding"]),
"CS 205": ("Introduces computer networks from physical signals to applications. Students learn the layered models and the protocols that make the Internet work.",
 ["Describe the OSI and TCP/IP models", "Explain addressing, routing, and switching basics", "Analyze common application protocols"],
 ["Network models and layering", "Physical and data link layers", "IP addressing and subnetting", "Transport layer: TCP and UDP", "LAN/WAN technologies"],
 ["Networking fundamentals", "Protocol analysis", "Foundation for security and advanced networks"]),
"CS 310": ("Explores selected contemporary topics in computer science at an intermediate level. Content is refreshed regularly to track current technologies and industry trends.",
 ["Engage with a modern computing topic in depth", "Relate new technologies to core CS principles", "Present and discuss technical material"],
 ["Selected modern topics (varies by offering)", "Case studies of current technologies", "Hands-on exploration", "Technical presentations"],
 ["Self-directed learning", "Adaptability to new technologies", "Technical communication"]),
"CS 413": ("Studies how humans interact with computers and how to design interfaces people can use effectively. The course blends design principles with practical evaluation methods.",
 ["Apply usability and user-centered design principles", "Prototype and evaluate user interfaces", "Account for accessibility and human factors"],
 ["Human factors and perception", "Usability principles and heuristics", "User-centered design process", "Prototyping techniques", "Interface evaluation methods"],
 ["UI/UX design", "Usability evaluation", "User empathy"]),
"H 102": ("Discusses the ethical and professional responsibilities of computing practitioners, from intellectual property to privacy in the age of data.",
 ["Apply ethical frameworks to computing dilemmas", "Understand professional codes of conduct", "Discuss privacy, IP, and digital responsibility"],
 ["Ethical theories and frameworks", "Professional codes (ACM/IEEE)", "Intellectual property", "Privacy and data protection", "Computer crime and liability"],
 ["Ethical judgment", "Professional responsibility", "Awareness of legal context"]),
"CS 301": ("Examines the principles underlying programming languages: how they are defined, what their constructs mean, and how paradigms differ.",
 ["Compare imperative, functional, and logic paradigms", "Analyze syntax and semantics of language constructs", "Evaluate type systems and binding strategies"],
 ["Syntax and semantics", "Names, bindings, and scope", "Data types and type checking", "Control structures and subprograms", "Functional and logic paradigms"],
 ["Language evaluation", "Paradigm flexibility", "Deeper programming insight"]),
"CS 303": ("An advanced treatment of operating systems covering modern concerns such as virtualization, distributed coordination, and OS-level security.",
 ["Analyze advanced memory and scheduling techniques", "Explain virtualization concepts", "Discuss distributed OS and security issues"],
 ["Advanced process and memory management", "Virtualization and hypervisors", "Distributed systems concepts", "OS security mechanisms", "Case studies of real systems"],
 ["Advanced systems analysis", "Virtualization literacy", "Security awareness at OS level"]),
"CS 304": ("Deepens software engineering practice with architecture, design patterns, and modern team methodologies, preparing students for industrial-scale development.",
 ["Apply common design patterns appropriately", "Design software architectures", "Plan and manage iterative development"],
 ["Software architecture styles", "Design patterns (GoF)", "Agile methods and Scrum", "Testing strategies", "Configuration management and DevOps basics"],
 ["Architectural design", "Pattern-based development", "Team project management"]),
"CS 307": ("Introduces the algorithms and mathematics of computer graphics, from drawing primitives to rendering 3D scenes, with hands-on programming.",
 ["Apply 2D/3D transformations using matrices", "Implement basic rendering pipeline stages", "Use a graphics API to build interactive scenes"],
 ["Graphics pipeline overview", "2D/3D transformations", "Viewing and projection", "Rasterization and clipping", "Shading and lighting models"],
 ["Graphics programming", "Geometric reasoning", "Visual computing foundations"]),
"CS 312": ("Covers the logic programming paradigm in which programs are sets of facts and rules. Students use Prolog to solve symbolic and AI-oriented problems declaratively.",
 ["Write Prolog programs using facts, rules, and queries", "Trace unification and backtracking", "Apply logic programming to AI problems"],
 ["Logic programming concepts", "Prolog syntax: facts, rules, queries", "Unification and resolution", "Lists and recursion in Prolog", "Applications in knowledge representation"],
 ["Declarative thinking", "Symbolic problem solving", "AI foundations"]),
"CS 311": ("Studies dynamic languages such as Python and JavaScript that power modern scripting and web development, focusing on their flexible runtime features.",
 ["Exploit dynamic typing and first-class functions", "Build scripts that automate practical tasks", "Develop small web-oriented applications"],
 ["Dynamic typing and runtime evaluation", "Functions as first-class objects", "Scripting and automation", "Rapid web development", "Comparison with static languages"],
 ["Rapid prototyping", "Scripting and automation", "Multi-language versatility"]),
"CS 313": ("Introduces cloud computing: how computation, storage, and services are delivered over the Internet at scale, and how applications are deployed to the cloud.",
 ["Distinguish IaaS, PaaS, and SaaS models", "Explain virtualization and elasticity", "Deploy a simple application to a cloud platform"],
 ["Cloud service and deployment models", "Virtualization and containers", "Cloud storage", "Scalability and elasticity", "Cloud security basics"],
 ["Cloud deployment", "Modern infrastructure literacy", "Scalable system design awareness"]),
"CS 305": ("Builds on networking fundamentals to cover routing protocols, network design, wireless technologies, and performance management in real networks.",
 ["Configure and analyze routing protocols", "Evaluate network performance", "Design small to medium networks"],
 ["Routing algorithms and protocols (RIP, OSPF, BGP)", "Wireless and mobile networks", "Network performance and QoS", "Network design and management", "IPv6"],
 ["Network design", "Protocol configuration", "Performance troubleshooting"]),
"CS 306": ("Covers how compilers translate high-level source code into executable form, walking through every phase from scanning to code generation.",
 ["Build lexical analyzers and parsers", "Perform semantic analysis with symbol tables", "Generate and optimize intermediate code"],
 ["Lexical analysis and regular expressions", "Context-free grammars and parsing", "Syntax-directed translation", "Semantic analysis", "Code generation and optimization"],
 ["Language tooling", "Parsing techniques", "Deep understanding of program execution"]),
"CS 308": ("Introduces digital image processing: representing images digitally and transforming them to enhance, analyze, or compress visual information.",
 ["Apply point and spatial filtering operations", "Perform image segmentation", "Explain common compression techniques"],
 ["Image fundamentals and color models", "Enhancement in spatial and frequency domains", "Filtering and edge detection", "Segmentation", "Compression basics"],
 ["Image analysis", "Algorithmic visual processing", "Foundation for vision and pattern recognition"]),
"CS 309": ("Studies microprocessors at the register level and teaches assembly language programming, revealing exactly how software drives hardware.",
 ["Program in assembly using registers and addressing modes", "Handle interrupts and subroutines", "Interface processors with memory and I/O"],
 ["Microprocessor architecture", "Assembly instructions and addressing modes", "Stack and subroutines", "Interrupts", "Memory and I/O interfacing"],
 ["Low-level programming", "Hardware interfacing", "Embedded systems foundation"]),
"CS 404": ("Covers systems whose components run on multiple machines that must coordinate over a network, including the models and algorithms that keep them consistent and fault tolerant.",
 ["Explain distributed architectures and communication", "Reason about consistency and replication", "Describe fault-tolerance techniques"],
 ["Client-server and peer-to-peer models", "Remote invocation and messaging", "Clock synchronization", "Consistency and replication", "Fault tolerance and consensus basics"],
 ["Distributed reasoning", "Scalable architecture design", "Reliability engineering awareness"]),
"CS 314": ("Introduces digital signal processing: representing signals digitally and designing systems that filter and transform them, with applications from audio to communications.",
 ["Sample and reconstruct analog signals correctly", "Analyze signals with Fourier techniques", "Design basic digital filters"],
 ["Sampling and quantization", "Discrete-time signals and systems", "Z-transform", "Discrete Fourier transform and FFT", "FIR/IIR filter design"],
 ["Signal analysis", "Filter design", "Mathematical computing"]),
"CS 315": ("Teaches end-to-end mobile application development for modern platforms, from designing responsive UIs to integrating device features and backend services.",
 ["Build multi-screen mobile apps with modern frameworks", "Manage application state effectively", "Integrate REST APIs and device capabilities"],
 ["Mobile UI design and navigation", "State management", "Networking and REST integration", "Local storage", "Device features (camera, location, notifications)", "Publishing basics"],
 ["Mobile development", "API integration", "Full app life-cycle experience"]),
"CS 316": ("Covers modeling real systems and simulating them on a computer to study behavior that is too costly or complex to experiment with directly.",
 ["Build discrete-event simulation models", "Generate and test random variates", "Validate models and analyze output statistically"],
 ["Modeling concepts", "Random number generation", "Discrete-event simulation", "Queueing system models", "Output analysis and validation"],
 ["System modeling", "Statistical analysis", "Experimental design"]),
"BS 203": ("Covers ordinary differential equations and the analytical techniques used to solve them, with applications to modeling dynamic physical and engineering systems.",
 ["Solve first and second order ODEs", "Apply Laplace transforms", "Model real systems with differential equations"],
 ["First-order ODEs", "Linear higher-order ODEs", "Laplace transform methods", "Systems of ODEs", "Engineering applications"],
 ["Mathematical modeling of dynamics", "Analytical solving", "Engineering mathematics"]),
"CS 401": ("Introduces artificial intelligence: building systems that search, reason, and learn. The course covers classical AI techniques and previews modern machine learning.",
 ["Apply uninformed and heuristic search strategies", "Represent knowledge and perform inference", "Describe basic learning approaches"],
 ["Intelligent agents", "Search: BFS, DFS, A*", "Game playing and adversarial search", "Knowledge representation and reasoning", "Intro to machine learning", "Expert systems"],
 ["AI problem formulation", "Heuristic design", "Foundation for ML and NLP"]),
"H 201": ("Covers quality assurance and control principles and how organizations build quality into processes and products, including international standards.",
 ["Apply quality management principles", "Use basic quality control tools", "Relate standards such as ISO to technical work"],
 ["Quality concepts and evolution", "Total quality management", "Quality control tools", "Standards (ISO 9001)", "Process improvement"],
 ["Quality mindset", "Process analysis", "Standards literacy"]),
"CS 402": ("Studies how to protect information and networks from attack. Students learn cryptographic foundations and the defensive mechanisms used in real systems.",
 ["Apply symmetric and asymmetric cryptography concepts", "Explain authentication and key management", "Configure basic network defenses"],
 ["Security goals and attacks", "Symmetric and public-key cryptography", "Hashing and digital signatures", "Authentication protocols", "Firewalls and intrusion detection"],
 ["Security analysis", "Cryptography literacy", "Defensive system design"]),
"CS 403": ("Covers the foundations of machine learning: algorithms that improve from data. Students implement core methods and learn to evaluate them rigorously.",
 ["Implement regression and classification algorithms", "Apply clustering to unlabeled data", "Evaluate models and avoid overfitting"],
 ["Supervised vs unsupervised learning", "Linear and logistic regression", "Decision trees and k-NN", "Clustering (k-means)", "Model evaluation and validation", "Intro to neural networks"],
 ["ML model building", "Data-driven reasoning", "Model evaluation"]),
"CS 405": ("Explores selected advanced topics in computer science, updated to reflect emerging technologies and current research directions.",
 ["Investigate an advanced computing topic in depth", "Read and discuss technical literature", "Produce a project or study on the topic"],
 ["Advanced selected topics (varies by offering)", "Recent research directions", "Hands-on projects", "Seminar discussions"],
 ["Research orientation", "Independent learning", "Advanced technical depth"]),
"CS 406": ("Introduces big data: storing and analyzing datasets too large for traditional tools, using distributed processing ecosystems.",
 ["Explain big data characteristics and architectures", "Use distributed processing frameworks", "Analyze large datasets end-to-end"],
 ["Big data concepts (volume, velocity, variety)", "Distributed file systems (HDFS)", "MapReduce and Spark", "NoSQL databases", "Big data analytics pipelines"],
 ["Large-scale data processing", "Distributed tools usage", "Data engineering basics"]),
"CS 407": ("Covers computer Arabization: the techniques required for software to process, display, and understand Arabic, from encodings to language-specific challenges.",
 ["Handle Arabic text encoding and rendering", "Localize software for Arabic users", "Address Arabic NLP challenges"],
 ["Arabic character encodings (Unicode)", "Bidirectional text rendering", "Arabic morphology challenges", "Software localization", "Arabic text processing tools"],
 ["Localization engineering", "Arabic text processing", "Culturally-aware software design"]),
"CS 408": ("Introduces virtual reality: building immersive 3D environments and the hardware and software that make presence and interaction possible.",
 ["Model 3D environments for VR", "Implement interaction in immersive scenes", "Evaluate VR usability and comfort"],
 ["VR concepts and hardware", "3D modeling for VR", "Tracking and interaction techniques", "Rendering for head-mounted displays", "VR application development"],
 ["Immersive application development", "3D interaction design", "Emerging-tech experience"]),
"CS 410": ("Covers the Internet of Things: networks of sensors and embedded devices that observe and act on the physical world, and the platforms that connect them.",
 ["Describe IoT architectures and protocols", "Interface sensors with embedded controllers", "Build a connected IoT prototype"],
 ["IoT architecture layers", "Sensors and embedded platforms", "Communication protocols (MQTT, CoAP)", "Cloud integration", "IoT security and privacy"],
 ["Embedded prototyping", "Connected systems design", "Sensor data handling"]),
"CS 416": ("Introduces knowledge discovery in databases: the full pipeline of preparing data and mining it for useful, previously unknown patterns.",
 ["Prepare and clean data for mining", "Apply association, classification, and clustering methods", "Evaluate and interpret discovered patterns"],
 ["KDD process", "Data preprocessing", "Association rule mining", "Classification techniques", "Clustering and outlier detection"],
 ["Data mining", "Pattern interpretation", "Analytical pipelines"]),
"CS 498": ("The first phase of the capstone graduation project. Teams identify a real problem, study it, and produce a complete analysis, design, and project plan.",
 ["Define a real-world problem and its scope", "Perform requirements analysis and system design", "Plan project work and deliver formal documentation"],
 ["Problem identification and literature review", "Requirements engineering", "System analysis and design", "Project planning", "Proposal writing and presentation"],
 ["Project scoping", "Team collaboration", "Formal documentation and presentation"]),
"CS 302": ("Covers writing programs that exploit multiple processors at once, including the architectures, models, and pitfalls of parallel computing.",
 ["Write multithreaded programs safely", "Apply parallel decomposition strategies", "Measure and improve parallel performance"],
 ["Parallel architectures", "Threads and synchronization", "Shared-memory programming", "Message passing basics", "Performance and speedup analysis"],
 ["Concurrent programming", "Performance engineering", "Modern multicore utilization"]),
"CS 419": ("Covers deep learning: multi-layer neural networks that learn rich representations, powering modern vision, speech, and language systems.",
 ["Train neural networks with backpropagation", "Build convolutional and recurrent architectures", "Apply deep models to vision/language tasks"],
 ["Neural network fundamentals", "Backpropagation and optimization", "Convolutional neural networks", "Recurrent networks and sequence models", "Regularization", "Deep learning frameworks"],
 ["Deep model development", "Framework proficiency", "State-of-the-art ML application"]),
"CS 409": ("Studies computer vision: enabling machines to extract meaning from images and video, from classic feature methods to recognition systems.",
 ["Extract and match visual features", "Implement object detection and recognition pipelines", "Analyze motion in video"],
 ["Image features and matching", "Object detection and recognition", "Segmentation for vision", "Motion and tracking", "Vision applications"],
 ["Vision system building", "Visual data analysis", "Applied AI"]),
"CS 411": ("Covers systematic software testing and the broader practice of assuring quality, from designing effective test cases to automating them.",
 ["Design black-box and white-box test cases", "Perform unit, integration, and system testing", "Automate tests and measure quality"],
 ["Testing levels and strategies", "Test case design techniques", "Unit testing and test automation", "Defect tracking", "Quality metrics and reviews"],
 ["Test engineering", "Automation", "Quality-driven development"]),
"CS 412": ("An advanced security course focused on offense-informed defense: how systems are attacked and how to detect, investigate, and harden against those attacks.",
 ["Conduct basic penetration testing ethically", "Analyze malware behavior at a high level", "Apply incident response and forensics basics"],
 ["Ethical hacking methodology", "Vulnerability assessment", "Malware analysis overview", "Digital forensics basics", "Security management and policies"],
 ["Offensive-defensive security skills", "Incident handling", "Security assessment"]),
"CS 414": ("Introduces natural language processing: making computers understand and generate human language, from text statistics to neural language applications.",
 ["Preprocess and represent text computationally", "Build language models and classifiers", "Implement applications such as sentiment analysis"],
 ["Text preprocessing and tokenization", "Language modeling", "Text classification and sentiment analysis", "Word embeddings", "Applications: translation, chatbots"],
 ["Text analytics", "Language application building", "Applied ML on text"]),
"CS 415": ("Covers soft computing: techniques that tolerate imprecision — fuzzy logic, evolutionary algorithms, and neural methods — to solve problems exact methods cannot.",
 ["Design fuzzy inference systems", "Apply genetic algorithms to optimization", "Combine soft techniques in hybrid systems"],
 ["Fuzzy sets and fuzzy logic", "Fuzzy inference systems", "Genetic algorithms", "Neural approaches", "Hybrid soft computing"],
 ["Approximate reasoning", "Heuristic optimization", "Adaptive system design"]),
"CS 417": ("Studies pattern recognition: assigning inputs such as images or signals to categories using statistical and learning-based classifiers.",
 ["Extract and select discriminative features", "Implement statistical classifiers", "Evaluate recognition system performance"],
 ["Pattern recognition pipeline", "Feature extraction and selection", "Bayesian and statistical classifiers", "Neural classifiers", "Applications in image/signal recognition"],
 ["Classifier design", "Feature engineering", "Recognition system evaluation"]),
"CS 418": ("Introduces game programming: the loops, physics, graphics, and design that make interactive games, built hands-on with a modern game engine.",
 ["Implement game loops and real-time logic", "Integrate graphics, physics, and audio", "Design and build a complete small game"],
 ["Game architecture and loops", "2D/3D graphics in engines", "Physics and collision", "Input, audio, and UI", "Game design principles", "Building a complete game project"],
 ["Game development", "Engine proficiency", "Creative technical design"]),
"CS 420": ("Covers data communications: how bits physically travel between machines, including signals, media, encoding, and error handling.",
 ["Explain signal encoding and modulation", "Analyze multiplexing and switching techniques", "Apply error detection and correction"],
 ["Signals and transmission media", "Encoding and modulation", "Multiplexing", "Error detection and correction", "Switching techniques"],
 ["Communication-layer understanding", "Signal analysis", "Telecom fundamentals"]),
"CS 499": ("The second phase of the capstone graduation project. Teams implement, test, and deploy the system designed in phase one, then defend the finished work.",
 ["Implement the designed system to completion", "Test, document, and deploy the product", "Present and defend the project professionally"],
 ["Implementation and integration", "Testing and quality assurance", "Deployment", "Final documentation", "Presentation and defense"],
 ["End-to-end delivery", "Professional presentation", "Real-world engineering experience"]),
}


def format_description(overview, objectives, topics, skills, prereq_text):
    parts = ["Course Overview:\n" + overview]
    parts.append("Learning Objectives:\n" + "\n".join(f"- {o}" for o in objectives))
    parts.append("Topics Covered:\n" + "\n".join(f"- {t}" for t in topics))
    parts.append("Skills Gained:\n" + "\n".join(f"- {s}" for s in skills))
    parts.append("Prerequisite: " + prereq_text)
    return "\n\n".join(parts)


conn = sqlite3.connect('academic_advisor.db')
cur = conn.cursor()

cols = [row[1] for row in cur.execute("PRAGMA table_info(courses)")]
if "description" not in cols:
    cur.execute("ALTER TABLE courses ADD COLUMN description VARCHAR")

updated = 0
skipped = 0
for code, (overview, objectives, topics, skills) in COURSES.items():
    row = cur.execute("SELECT prerequisite_code FROM courses WHERE code=?", (code,)).fetchone()
    if not row:
        skipped += 1
        continue
    prereq_code = row[0]
    if prereq_code:
        pr = cur.execute("SELECT name FROM courses WHERE code=?", (prereq_code,)).fetchone()
        prereq_text = f"{pr[0]} ({prereq_code})" if pr else prereq_code
    else:
        prereq_text = "None"
    cur.execute("UPDATE courses SET description=? WHERE code=?",
                (format_description(overview, objectives, topics, skills, prereq_text), code))
    updated += 1

conn.commit()
conn.close()
print(f"Done. Updated: {updated}, skipped (course not found): {skipped}")
